### ISSUE TITLE
Symfony\Component\Security\Acl\Exception and Symfony 3

### ISSUE THREAD

**Issue by nguyenthaialan** [nilportugues/symfony-jsonapi#18]
Attempted to load class "Exception" from namespace "Symfony\Component\Security\Acl\Exception".
Did you forget a "use" statement for "Symfony\Component\Config\Definition\Exception\Exception"?

in vendor/nilportugues/jsonapi-bundle/src/Serializer/JsonApiSerializer.php at line 103

**Comment by nilportugues** [comment]
@nguyenthaialan True, I was missing a backslash in the \Exception declaration. Thanks.

This error is being thrown because you did not name your route or name is invalid in your mapping.

**Comment by nilportugues** [comment]
https://github.com/nilportugues/symfony-jsonapi/commit/e31151d1665c391f5835128f312328f652234083

Use release 1.3.3. Thanks.
