### ISSUE TITLE
DateTime object from doctrine goes to relationships on included member

### ISSUE THREAD

**Issue by franbenz** [nilportugues/symfony-jsonapi#21]
When a DateTime object belongs to a top level entity it shows up as this
```
data: [
{
  type: "entidad1",
  id: "1",
  attributes: {
    fecha: {
      date: "2016-06-09 00:00:00",
      timezone_type: 3,
      timezone: "America/Asuncion"
    },...
```
But when the DateTime object is an attribute from an included entity it goes to the `relationships` member as this:
```
...
included: [
  {
    type: "entidad1",
    id: "1",
    attributes: {
      descripcion: "prueba"
    },
    relationships: {
      fecha: {
        data: [ ]
      },
    ...
```
Is this normal behaviour? Should I enable something for DateTime serializers to work?

**Comment by nilportugues** [comment]
@franbenz should not be empty at all. I'll try to reproduce the error.

Maybe you can provide a test with this bug as a PR to speed things a bit.

**Comment by franbenz** [comment]
Thanks for the fix.
After [this commit](https://github.com/nilportugues/php-json-api/commit/9a27b9ef9447c65a0554fd83a56b8f01ce27dfea#diff-dc206e020e956e8ccaef90201fc49374L143) the DateTime attribute does not appear in the `relationships` but neither it appears in the `attributes` member. Why should some attributes appear and others should not?

**Comment by nilportugues** [comment]
@franbenz thanks for pointing this out. Looking into it

**Comment by nilportugues** [comment]
@franbenz this made me build an additional piece of code in the api-transformer library that will solve this problem and many others :+1: 

This: https://github.com/nilportugues/php-json-api/blob/582c05ad34195f24ca6939b66ca15737d7c56519/src/JsonApiTransformer.php#L64

**Comment by franbenz** [comment]
Thanks, it's working. The DateTime is where it belongs now.
