### ISSUE TITLE
JsonApiSerializer doesn't include filterOutIncludedResources method

### ISSUE THREAD

**Issue by franbenz** [nilportugues/symfony-jsonapi#22]
Hi @nilportugues 
Why does JsonApiSerializer(from this bundle) doesn't include the filterOutIncludedResources method like the JsonApiSerializer from [NilPortugues\Api\JsonApi](https://github.com/nilportugues/php-json-api/blob/b203f67aedfa089c5af5112bf48ebc112bee16d4/src/JsonApiSerializer.php#L92)?
What's the difference between this two JsonApiSerializers?
I'd like to filter out included objects with this bundle too. How could I achieve it?

**Comment by nilportugues** [comment]
@franbenz clearly a tiny bug. 

https://github.com/nilportugues/symfony-jsonapi/releases/tag/1.5.1
