### ISSUE TITLE
Use Symfony Seriailzer

### ISSUE THREAD

**Issue by davidbarratt** [nilportugues/symfony-jsonapi#28]
Perhaps it would be better if this library used the [Symfony Serializer Component](http://symfony.com/doc/current/components/serializer.html)? Is there a reason it doesn't?

This is the way Drupal's [JSON API](https://www.drupal.org/project/jsonapi) works, perhaps we could collaborate with them?

**Comment by nilportugues** [comment]
This library is not symfony only. Might have a look thou.
