### ISSUE TITLE
ordering of attributes in the output

### ISSUE THREAD

**Issue by mmucklo** [nilportugues/symfony-jsonapi#7]
Is there anyway to sort the attribute keys before outputting them (or at least have the option to do a sort)?

The reflection does seem to pick out the properties "in order" from the Class file, however if you have a sub-class it can be difficult then to keep things strictly alphabetical, especially if there are attributes defined in both files.

**Comment by nilopc** [comment]
This is definately one configurable parameter I could make available in the configuration. Nice idea.

While it adds little value to the data transformation or data usage, I understand pretty output is something craftmans take into account when choosing a package ;)

**Comment by nilportugues** [comment]
@mmucklo available since https://github.com/nilportugues/symfony-jsonapi/releases/tag/1.5.0 because of https://github.com/nilportugues/php-json-api/releases/tag/2.3.0
