### ISSUE TITLE
Closures are not supported in Serializer

### ISSUE THREAD

**Issue by AlexandreKilian** [nilportugues/symfony-jsonapi#9]
I'm getting this Exception after following the instructions pretty much 1:1. What could be causing this?

**Comment by nilportugues** [comment]
@AlexandreKilian Well, this happens to the normal behaviour for PHP. You cannot serialize closures, therefore it will throw an exception.

The serializer is capturing this because, otherwise, a Fatal Error is thrown.

**Comment by AlexandreKilian** [comment]
@nilportugues i get that, but I didn't try to serialize any closures, just a basic doctrine entity

**Comment by nilportugues** [comment]
Hmm @AlexandreKilian this might be related to the circular references in Doctrine (their Proxy classes...). 

There's already an issue for this: https://github.com/nilportugues/symfony-jsonapi/issues/3

**Comment by franbenz** [comment]
Sorry to reopen an old issue. 
I'm tring to serialize an Article entity which has a manyToOne relation with Author. When I fetch the Article with the doctrine find method, the autor entity isn't loaded yet because of lazy loading. 
The error appears when I use serialize on the article.
Does this means I must use fetch: EAGER in my entities so that serializations work?
Thanks

**Comment by nilportugues** [comment]
You cannot serialize a closure. It's a PHP issue. 

You can definately create a piece of code, store it and run eval or bind it to something and make it run like https://github.com/jeremeamia/super_closure does.

Back to doctrine, disable EAGER and use the real thing. In the end, the serializer should not be aware of doctrine, eloquent or prophel or any custom solution. It only handles with objects. 

The only way I can actually make that work is actually write a Doctrine driver for the serializer (it's on the roadmap!) or detect that's a closure and force it to run. Yet, if it requires arguments it will fail.

**Comment by franbenz** [comment]
Thanks, I already understood the issue. What I was really wondering was how did you manage to avoid it.

In [this line](https://github.com/nilportugues/symfony-jsonapi/blame/master/README.md#L246
) from the readme example, you don't seem to be doing anything special but still get to serialize the entities related to the post object(comments, user, etc.). In my case, if I don't use the EAGER fetch mode, the related entities would not be fetched and I would only have closures.

**Comment by nilportugues** [comment]
@franbenz maybe I should fix that in the docs. Thanks for pointing that out.

I'm willing to add fixes to the serializer used to make life easier to the users of this library, not that it doesn't do lots already, but there are some rough edge-cases to handle such as closure and cyclical references.

**Comment by franbenz** [comment]
If you give me some guidelines, I could fix the docs and create a pull request.

**Comment by franbenz** [comment]
When I said I understood the issue, I didn't mean that I solved it. Could you help me avoid it?

**Comment by franbenz** [comment]
I'm sorry, I read the mail notification of [this comment](https://github.com/nilportugues/symfony-jsonapi/issues/9#issuecomment-224838685) where you originally said "Back to doctrine, **disable** EAGER and use the real thing." That was what puzzled me. Just now I read the current and edited comment and saw it says **enable**. And it all makes sense now.

**Comment by AlexandreKilian** [comment]
This issue could maybe be handled by giving the option of using alternate serializers... This Bundle here uses the Symfony Serializer by default, JMS as an alternative and gives the option to use another: https://github.com/steffenbrem/JsonApiBundle
It's not actively being developed at the moment and doesn't provide the full spec like this one, but maybe it could be used for inspiration since you can serialize closures with JMS
